name: Forge CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Forge CLI
        run: npm install --global @forge/cli

      - name: Set Forge usage analytics
        run: forge settings set usage-analytics true

      - name: Run Forge lint
        run: forge lint

  deploy_staging:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Forge CLI
        run: npm install --global @forge/cli

      - name: Set Forge usage analytics
        run: forge settings set usage-analytics true

      - name: Deploy to Staging
        run: forge deploy -e staging

      - name: Install Forge app on Staging
        run: forge install --upgrade --site MYSITE.atlassian.com --product confluence --non-interactive -e staging

  deploy_production:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Forge CLI
        run: npm install --global @forge/cli

      - name: Set Forge usage analytics
        run: forge settings set usage-analytics true

      - name: Deploy to Production
        run: forge deploy -e production
